//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_School
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public int PhoneNumber { get; set; }
        public string EmaiL { get; set; }
        public Nullable<int> Stu_ID { get; set; }
        public string CourseName { get; set; }
        public string ClassName { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public string Grade { get; set; }
    }
}
